### ISSUE TITLE
请问：为什么会丢弃掉那么多的样本？

### ISSUE THREAD

**Issue by 24kkchunshuai** [zhusleep/tagger_rewriter#1]
您好，我在运行代码时为什么样本丢弃了一万多个：

数据总数  2000 丢弃样本数目  0
信息插入 0
指代消歧义 0
数据总数  5030 丢弃样本数目  12968
信息插入 3591
指代消歧义 1439

是原本就丢弃了这么多还是代码存在问题？
而且运行20个epoch后的结果为：

Epoch 19, lr 0.000030:   loss=0.28148
{'rouge-1': {'f': 0.6597516436586924, 'p': 0.6978209847056074, 'r': 0.6489965442322307}, 'rouge-2': {'f': 0.5517651252907505, 'p': 0.5856899081900819, 'r': 0.5433706683702515}, 'rouge-l': {'f': 0.6387673727919192, 'p': 0.6771164357462252, 'r': 0.6250713962161332}, 'em': 0.0545}

数据没有达到最好，是训练epoch太少吗？还是样本丢弃的太多了。

**Comment by zhusleep** [comment]
我刚刚跑了一下，结果如下
数据总数  15495 丢弃样本数目  2503
信息插入 9095
指代消歧义 6400

没问题的呢。要不你再看看dataset.py？

**Comment by 24kkchunshuai** [comment]
好的，我再看看

**Comment by 24kkchunshuai** [comment]
问题解决了，在读取txt文件的时候编码没有设置为utf-8，所以汉字乱码了，导致丢弃了大量样本。添加encoding='utf-8'后解决。

```
valid_df = pd.read_table('../data/dialog-rewrite/test.csv', sep=",", names=['a','b','current','label'], encoding='utf-8', dtype=str)
```
