### ISSUE TITLE
模型训练问题

### ISSUE THREAD

**Issue by Maxhyl** [zhusleep/tagger_rewriter#3]
您好，我在训练模型的时候，发现模型都是在前几轮的分数比较高，后面训练的分数都是无法超越前面的，模型训练后的效果也不太理想，请问如果要优化的话可以从哪方面入手？自己新增训练数据吗

**Comment by SivilTaram** [comment]
@Maxhyl 我们最近提出了一个全新的重写模型，欢迎在我们的[code](https://github.com/microsoft/ContextualSP/blob/master/incomplete_utterance_rewriting/README_zh.md)/[paper](https://arxiv.org/abs/2009.13166) 上做进一步的优化

**Comment by gaoxing153** [comment]
> 您好，我在训练模型的时候，发现模型都是在前几轮的分数比较高，后面训练的分数都是无法超越前面的，模型训练后的效果也不太理想，请问如果要优化的话可以从哪方面入手？自己新增训练数据吗

您好，请问你在构建模型的时候使用的transformers是哪一个版本的，我在使用4.2.1时候运行程序会报错ModuleNotFoundError: No module named 'transformers.utils_encoder_decoder'，冒昧打扰，非常不好意思，希望得到您的回复。

**Comment by Maxhyl** [comment]
> > 您好，我在训练模型的时候，发现模型都是在前几轮的分数比较高，后面训练的分数都是无法超越前面的，模型训练后的效果也不太理想，请问如果要优化的话可以从哪方面入手？自己新增训练数据吗
> 
> 您好，请问你在构建模型的时候使用的transformers是哪一个版本的，我在使用4.2.1时候运行程序会报错ModuleNotFoundError: No module named 'transformers.utils_encoder_decoder'，冒昧打扰，非常不好意思，希望得到您的回复。

注释掉就行了，没用到的函数

**Comment by gaoxing153** [comment]
> > > 您好，我在训练模型的时候，发现模型都是在前几轮的分数比较高，后面训练的分数都是无法超越前面的，模型训练后的效果也不太理想，请问如果要优化的话可以从哪方面入手？自己新增训练数据吗
> > 
> > 
> > 您好，请问你在构建模型的时候使用的transformers是哪一个版本的，我在使用4.2.1时候运行程序会报错ModuleNotFoundError: No module named 'transformers.utils_encoder_decoder'，冒昧打扰，非常不好意思，希望得到您的回复。
> 
> 注释掉就行了，没用到的函数

好的，非常感谢

**Comment by zhusleep** [comment]
transformer是3.0.3，应该是这样。增加数据是有用的。用更大的预训练模型也是有用的。


 
---原始邮件---
发件人: "xing gao"<notifications@github.com&gt;
发送时间: 2021年1月19日 10:47:54
收件人: "zhusleep/tagger_rewriter"<tagger_rewriter@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [zhusleep/tagger_rewriter] 模型训练问题 (#3)




    
您好，我在训练模型的时候，发现模型都是在前几轮的分数比较高，后面训练的分数都是无法超越前面的，模型训练后的效果也不太理想，请问如果要优化的话可以从哪方面入手？自己新增训练数据吗
  
您好，请问你在构建模型的时候使用的transformers是哪一个版本的，我在使用4.2.1时候运行程序会报错ModuleNotFoundError: No module named 'transformers.utils_encoder_decoder'，冒昧打扰，非常不好意思，希望得到您的回复。
  
注释掉就行了，没用到的函数
  
好的，非常感谢
